<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Gateway', 'doctrine');

/**
 * BaseGateway
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $php_class
 * @property Doctrine_Collection $Clients
 * @property Doctrine_Collection $Transactions
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getPhpClass()     Returns the current record's "php_class" value
 * @method Doctrine_Collection getClients()      Returns the current record's "Clients" collection
 * @method Doctrine_Collection getTransactions() Returns the current record's "Transactions" collection
 * @method Gateway             setName()         Sets the current record's "name" value
 * @method Gateway             setPhpClass()     Sets the current record's "php_class" value
 * @method Gateway             setClients()      Sets the current record's "Clients" collection
 * @method Gateway             setTransactions() Sets the current record's "Transactions" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGateway extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gateway');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('php_class', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Client as Clients', array(
             'local' => 'id',
             'foreign' => 'gateway_id'));

        $this->hasMany('Transaction as Transactions', array(
             'local' => 'id',
             'foreign' => 'gateway_id'));
    }
}