<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClientGatewayData', 'doctrine');

/**
 * BaseClientGatewayData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property string $gateway_key
 * @property string $gateway_secret
 * @property string $gateway_other
 * @property Client $Client
 * 
 * @method integer           getClientId()       Returns the current record's "client_id" value
 * @method string            getGatewayKey()     Returns the current record's "gateway_key" value
 * @method string            getGatewaySecret()  Returns the current record's "gateway_secret" value
 * @method string            getGatewayOther()   Returns the current record's "gateway_other" value
 * @method Client            getClient()         Returns the current record's "Client" value
 * @method ClientGatewayData setClientId()       Sets the current record's "client_id" value
 * @method ClientGatewayData setGatewayKey()     Sets the current record's "gateway_key" value
 * @method ClientGatewayData setGatewaySecret()  Sets the current record's "gateway_secret" value
 * @method ClientGatewayData setGatewayOther()   Sets the current record's "gateway_other" value
 * @method ClientGatewayData setClient()         Sets the current record's "Client" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientGatewayData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_gateway_data');
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('gateway_key', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gateway_secret', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gateway_other', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}