<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Client', 'doctrine');

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $client_key
 * @property string $client_secret
 * @property integer $gateway_id
 * @property Gateway $Gateway
 * @property ClientGatewayData $ClientGatewayData
 * @property Doctrine_Collection $Transactions
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getClientKey()         Returns the current record's "client_key" value
 * @method string              getClientSecret()      Returns the current record's "client_secret" value
 * @method integer             getGatewayId()         Returns the current record's "gateway_id" value
 * @method Gateway             getGateway()           Returns the current record's "Gateway" value
 * @method ClientGatewayData   getClientGatewayData() Returns the current record's "ClientGatewayData" value
 * @method Doctrine_Collection getTransactions()      Returns the current record's "Transactions" collection
 * @method Client              setName()              Sets the current record's "name" value
 * @method Client              setClientKey()         Sets the current record's "client_key" value
 * @method Client              setClientSecret()      Sets the current record's "client_secret" value
 * @method Client              setGatewayId()         Sets the current record's "gateway_id" value
 * @method Client              setGateway()           Sets the current record's "Gateway" value
 * @method Client              setClientGatewayData() Sets the current record's "ClientGatewayData" value
 * @method Client              setTransactions()      Sets the current record's "Transactions" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('client_key', 'string', 32, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('client_secret', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('gateway_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gateway', array(
             'local' => 'gateway_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ClientGatewayData', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $this->hasMany('Transaction as Transactions', array(
             'local' => 'id',
             'foreign' => 'client_id'));
    }
}