<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApiLog', 'doctrine');

/**
 * BaseApiLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $message
 * @property integer $errorcode
 * @property string $info
 * 
 * @method string  getMessage()   Returns the current record's "message" value
 * @method integer getErrorcode() Returns the current record's "errorcode" value
 * @method string  getInfo()      Returns the current record's "info" value
 * @method ApiLog  setMessage()   Sets the current record's "message" value
 * @method ApiLog  setErrorcode() Sets the current record's "errorcode" value
 * @method ApiLog  setInfo()      Sets the current record's "info" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApiLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('api_log');
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('errorcode', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('info', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}