<?php

/**
 * ApiLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApiLog');
    }
}