<?php

/**
 * ClientGatewayDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientGatewayDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientGatewayDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientGatewayData');
    }
}