<?php

/**
 * GatewayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GatewayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GatewayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gateway');
    }
}