<?php

/**
 * Client form.
 * sfDoctrineFormGenerator *
 * @package    cms
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormTemplate.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class ClientForm extends BaseClientForm
{
    public function configure()
    {

    }

    public function updateDefaultsFromObject()
    {
        parent::updateDefaultsFromObject(); // TODO: Change the autogenerated stub
        if(!$this->getObject()->client_secret){
            $this->setDefault('client_secret', sha1(md5(microtime())) . md5(time()));
        }
    }
}
