DefaultImage:
  connection: doctrine  
  actAs: [ImageBuilder]
  columns:
    name: string(255)
    title: string(255)
    image: {type: string(255), notnull: true} 

TextBlock:
  connection: doctrine
  actAs:
    I18n:
      fields: [text]
  columns:
    name: {type: string(255), notnull: true}
    title: {type: string(255)}
    text: string()
    application: string(32)
    module: string(32)
    special_mark: string(32)
    is_visible_for_admin: {type: boolean, default: false}
  indexes:
    section_index:
      fields: [application, module]


Gateway:
  connection: doctrine
  columns:
    name: {type: string(255), notnull: true}
    php_class: string(255)

ApiLog:
  connection: doctrine
  actAs: [Timestampable]
  columns:
    message: string(255)
    errorcode: integer
    info: string()

Client:
  connection: doctrine
  columns:
    name: {type: string(255), notnull: true}
    client_key: {type: string(32), unique: true, notnull: true}
    client_secret: {type: string(255), notnull: true}
    gateway_id: integer
  relations:
    Gateway: {foreignAlias: Clients, onDelete: SET NULL}

ClientGatewayData:
  connection: doctrine
  columns:
    client_id: {type: integer, notnull: true}
    gateway_key: string(255)
    gateway_secret: string(255)
    gateway_other: string(255)
  relations:
    Client: {type: one, foreignType: one, onDelete: CASCADE}

Transaction:
  connection: doctrine
  actAs: [Timestampable]
  columns:
    client_id: {type: integer, notnull: true}
    gateway_id: {type: integer, notnull: true}
    status: {type: enum, values: [pending, paid, cancelled], default: pending}
    sum: {type: float, notnull: true}
    currency: {type: string(32), notnull: true}
    product: string(255)
    description: string(255)
    hash: string(255)
    url_success: string()
    url_cancel: string()
    url_failure: string()
  relations:
    Gateway: {foreignAlias: Transactions, onDelete: CASCADE}
    Client: {foreignAlias: Transactions, onDelete: CASCADE}